services:
  # Nginx
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log/nginx:/var/log/nginx
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app-network

  # PHP-FPM
  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    ports:
      - 9000:9000
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
